### PR TITLE
Solutions in Kotlin

### PR DESCRIPTION
**Pull request by AndyBowes**
Completed Solutions.
Made Levenstein more functional

### CODE REVIEW

**Comment by AndyBowes** [comment]
Thanks Grant

Good evening last night.  Good to see some new faces at the Dojo, hope at
least some attend future sessions.

**Comment by AndyBowes** [comment]
Arggh, just seen that I have checked in a directory called 'New Folder'
rather than 'Sam_Andy_Kotlin'.

Are you able to rename this directory or shalll I do it this evening?

**Comment by relentless** [comment]
I've renamed it

**Comment by AndyBowes** [comment]
Thanks

**Pull request merged**
